### ISSUE TITLE
Authentication is broken again

### ISSUE THREAD

**Issue by hieronymousch** [flackdl/ifit-garmin-sync#4]
See https://github.com/La0/garmin-uploader/issues/28 for a solution.. 
Is simply redeploying going to solve it?

**Comment by flackdl** [comment]
Interesting, I just checked my installation and forced a sync and it authenticated just fine.  I wonder if the errors are transient (since garmin is apparently behind cloudflare maybe it's related to traffic volume when it behaves differently).  

I'm happy to merge their fix from https://github.com/La0/garmin-uploader/issues/28 when it's verified.  Let me know when that happens and I"ll update this repository.

**Comment by hieronymousch** [comment]
I actually managed to get it working (note to self: celery needs to run in the same session where the exports of user & pass were done) and sync is now working... So it seems to be a heroku - garmin traffic issue.
